FORMAT: 1A
HOST: http://gbptm-api-stage.herokuapp.com/api

# Great British Public Toilet Map
The GBPTM API is a service for collection, submission and discovery of Public Toilets in the UK

# GBPTM  API Root [/]
GBPTM API entry point

Offers affordances in the form of HTTP Link headers and HAL content.

## Retrieve Entry Point [GET]

+ Response 200 (application/hal+json)
    + Headers

            Link : <http://gbptm-api-stage.herokuapp.com/api/>;rel="self",<http:gbptm-api-stage.herokuapp.com/api/loos/>;rel="loos"

    + Body

            {
                "_links": {
                    "self": { "href": "/" },
                    "loos": { "href": "/loos" }
                }
            }

# Group Loos
Loos related resources of the **GBPTM API**

## Loos Collection [/loos]
### List all Loos [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Loo 1"
        }, {
          "id": 2, "name": "Loo 2"
        }]


