FORMAT: 1A
HOST: http://gbptm-api-stage.herokuapp.com/api

# Great British Public Toilet Map
The **GBPTM API** is a service for collection, submission and discovery of Public Toilets in the UK

# GBPTM  API Root [/]
**GBPTM API** entry point

Offers affordances in the form of HTTP Link headers and HAL content.

## Retrieve Entry Point [GET]

+ Response 200 (application/hal+json)
    + Headers

            Link : <http://gbptm-api-stage.herokuapp.com/api/>;rel="self",<http:gbptm-api-stage.herokuapp.com/api/loos/>;rel="loos"

    + Body

            {
                "_links": {
                    "self": { "href": "/" },
                    "loos": { "href": "/loos" }
                }
            }

# Group Loos
Loo-related resources of the **GBPTM API**

## Loo [/loos/{id}]
A **Loo** resource represents an individual publicly accessible toilet.

A Loo is represented as a [GeoJSON Feature](http://geojson.org/geojson-spec.html#feature-objects) 

The Loo resource has the following properties:

- _id
- type
- geohash
- geometry
- properties

+ Parameters
    + id (string) ... ID of the Loo ([an ObjectId](http://docs.mongodb.org/manual/reference/object-id/))

+ Model (application/hal+json)

    HAL+JSON representation of a Loo. In additon to its state representation in GeoJSON it is enhanced with affordances through HAL sections an HTTP Link headers.

    + Headers

            Link: <http://gbptm-api-stage.herokuapp.com/api/loos/5357d189003abe7007b41e56>

    + Body

            {
                "_links": {
                    "self": { "href": "/loos/5357d189003abe7007b41e56" }
                },
                _id: "5357d189003abe7007b41e56",
                type: "Feature",
                geohash: "u10j3z4qbcrg",
                properties: {
                    name: "Barkingside Recreation Ground"
                },
                geometry: {
                    type: "Point",
                    coordinates: [
                        0.08003711700439438,
                        51.587469736279594
                    ]
                }
            }

### Retrieve a single Loo [GET]
+ Response 200

    [Loo][]

## Loos Collection [/loos]
### List all Loos [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Loo 1"
        }, {
          "id": 2, "name": "Loo 2"
        }]


