import type { paintRules } from 'protomaps-leaflet';

type Theme = Parameters<typeof paintRules>[0];

/**
 * Adapted from [`greyscale`](https://github.com/protomaps/protomaps-leaflet/blob/fc1b260bcbfe37aede11c866a4ea39e23b5ad099/src/default_style/themes.ts#L361)
 */
export const mapTheme = {
  background: '#a3a3a3',
  earth: '#eeeeee',
  park_a: '#d2fff2',
  park_b: '#d2fff2',
  hospital: '#d0d0d0',
  industrial: '#c6c6c6',
  school: '#d0d0d0',
  wood_a: '#d2fff2',
  wood_b: '#d2fff2',
  pedestrian: '#fff',
  scrub_a: '#d2fff2',
  scrub_b: '#d2fff2',
  glacier: '#d2d2d2',
  sand: '#d2d2d2',
  beach: '#d2d2d2',
  aerodrome: '#c9c9c9',
  runway: '#f5f5f5',
  water: '#0a165e',
  pier: '#f4f4f4',
  zoo: '#c7c7c7',
  military: '#bfbfbf',

  tunnel_other_casing: '#b8b8b8',
  tunnel_minor_casing: '#b8b8b8',
  tunnel_link_casing: '#b8b8b8',
  tunnel_medium_casing: '#b8b8b8',
  tunnel_major_casing: '#b8b8b8',
  tunnel_highway_casing: '#b8b8b8',
  tunnel_other: '#d6d6d6',
  tunnel_minor: '#d6d6d6',
  tunnel_link: '#d6d6d6',
  tunnel_medium: '#d6d6d6',
  tunnel_major: '#d6d6d6',
  tunnel_highway: '#d6d6d6',

  transit_pier: '#b8b8b8',
  buildings: '#dfdfdd',

  minor_service_casing: '#cccccc',
  minor_casing: '#cccccc',
  link_casing: '#cccccc',
  medium_casing: '#cccccc',
  major_casing_late: '#cccccc',
  highway_casing_late: '#cccccc',
  other: '#e0e0e0',
  minor_service: '#e0e0e0',
  minor_a: '#ebebeb',
  minor_b: '#e0e0e0',
  link: '#ebebeb',
  medium: '#ebebeb',
  major_casing_early: '#cccccc',
  major: '#bbc',
  highway_casing_early: '#cccccc',
  highway: '#999',

  railway: '#222222',
  boundaries: '#5c5c5c',
  waterway_label: '#7a7a7a',

  bridges_other_casing: '#cccccc',
  bridges_minor_casing: '#cccccc',
  bridges_link_casing: '#cccccc',
  bridges_medium_casing: '#cccccc',
  bridges_major_casing: '#cccccc',
  bridges_highway_casing: '#cccccc',
  bridges_other: '#e0e0e0',
  bridges_minor: '#e0e0e0',
  bridges_link: '#ebebeb',
  bridges_medium: '#ebebeb',
  bridges_major: '#ebebeb',
  bridges_highway: '#ebebeb',

  roads_label_minor: '#888',
  roads_label_minor_halo: '#e0e0e0',
  roads_label_major: '#556',
  roads_label_major_halo: '#fff',
  ocean_label: '#7a7a7a',
  peak_label: '#5c5c5c',
  subplace_label: '#7a7a7a',
  subplace_label_halo: '#fff',
  city_circle: '#c2c2c2',
  city_circle_stroke: '#7a7a7a',
  city_label: '#474747',
  city_label_halo: '#fff',
  state_label: '#999999',
  state_label_halo: '#cccccc',
  country_label: '#858585',
} satisfies Theme;
