backend:
  name: github
  repo: public-convenience-ltd/toiletmap
  branch: ob/decap
  site_domain: localhost:3000
  base_url: https://localhost:3000
  auth_endpoint: api/decap-oauth
site_url: https://localhost:3000
display_url: https://localhost:3000
publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: "pages"
    label: "Pages"
    label_singular: 'Page'
    folder: content/pages
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts"
    create: true
    label: "Blog Posts"
    label_singular: 'Blog Post'
    folder: content/posts
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Social URL", name: "profileSocialUrl", widget: "string" }
      - { label: "Profile Image URL", name: "profilePictureUrl", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
