backend:
  name: github
  repo: public-convenience-ltd/toiletmap
  branch: ob/decap
  site_domain: toiletmap-git-ob-decap-public-convenience-ltd.vercel.app/
  base_url: https://toiletmap-git-ob-decap-public-convenience-ltd.vercel.app
  auth_endpoint: api/decap-oauth
site_url: https://toiletmap-git-ob-decap-public-convenience-ltd.vercel.app/
display_url: https://toiletmap-git-ob-decap-public-convenience-ltd.vercel.app/
publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: "pages"
    label: "Pages"
    label_singular: 'Documentation'
    folder: content/pages
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
