backend:
  name: github
  repo: public-convenience-ltd/toiletmap
  branch: ob/decap
  site_domain: toiletmap.org.uk
  base_url: https://toiletmap.org.uk
  auth_endpoint: api/decap-oauth
site_url: https://toiletmap.org.uk/
display_url: https://toiletmap.org.uk/
publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/pages/home.mdx"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Author", name: "author", widget: "string" }
