-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE public.toilets ALTER COLUMN updated_at TYPE timestamptz;
ALTER TABLE public.toilets ALTER COLUMN created_at TYPE timestamptz;
ALTER TABLE public.toilets ALTER COLUMN verified_at TYPE timestamptz;
