name: E2E Cypress Tests
on: push
jobs:
  cypress-e2e:
    name: Cypress E2E
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: toiletmap
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AUTH0_ISSUER_BASE_URL: https://gbptm.eu.auth0.com
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: https://www.toiletmap.org.uk/graphql
          AUTH0_PERMISSIONS_KEY: https://toiletmap.org.uk/permissions
          AUTH0_PROFILE_KEY: https://toiletmap.org.uk/profile
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 60
          browser: chrome
          spec: cypress/integration/*.ts
